dist: focal
language: node_js
node_js:
  - 14
  - 17
install:
  - npm install --force
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports # cmake
    packages:
    - gcc
    - g++
    - clang
    - cmake
    - cmake-data
